//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfDataApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Files
    {
        public int id { get; set; }
        public string FullPath { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> FileDate { get; set; }
        public Nullable<long> Size { get; set; }
    }
}
