//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WormGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameResults
    {
        public int Id { get; set; }
        public string Player { get; set; }
        public int Score { get; set; }
        public System.DateTime DT { get; set; }
    }
}
